// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function joinMorphemes(left, right) {
  if (left.TAG !== /* Prefix */0) {
    return left._0.name + right.join + right.name;
  }
  var l = left._0;
  return l.name + l.join + right.name;
}

console.log(joinMorphemes({
          TAG: /* Prefix */0,
          _0: {
            name: "o",
            join: "h"
          }
        }, {
          name: "la",
          join: "l"
        }));

exports.joinMorphemes = joinMorphemes;
/*  Not a pure module */
