// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Join$Keoda = require("./Join.bs.js");

function main(param) {
  console.log(Join$Keoda.fold({
            hd: {
              TAG: /* Prefix */0,
              _0: {
                name: "es",
                join: "h"
              }
            },
            tl: {
              hd: {
                TAG: /* Prefix */0,
                _0: {
                  name: "o",
                  join: "h"
                }
              },
              tl: {
                hd: {
                  TAG: /* Word */1,
                  _0: {
                    name: "la",
                    join: "l"
                  }
                },
                tl: {
                  hd: {
                    TAG: /* Word */1,
                    _0: {
                      name: "ir",
                      join: "l"
                    }
                  },
                  tl: /* [] */0
                }
              }
            }
          }));
  
}

main(undefined);

exports.main = main;
/*  Not a pure module */
