// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function joinMorphemes(left, right) {
  if (left.TAG !== /* Prefix */0) {
    return left._0.name + (right.join + right.name);
  }
  var l = left._0;
  return l.name + (l.join + right.name);
}

function join(left, right) {
  if (right.TAG === /* Prefix */0) {
    var r = right._0;
    return {
            TAG: /* Prefix */0,
            _0: {
              name: joinMorphemes(left, r),
              join: r.join
            }
          };
  }
  var r$1 = right._0;
  return {
          TAG: /* Word */1,
          _0: {
            name: joinMorphemes(left, r$1),
            join: r$1.join
          }
        };
}

function fold(wlist) {
  var foldl = function (_acc, _right) {
    while(true) {
      var right = _right;
      var acc = _acc;
      if (!right) {
        return acc;
      }
      _right = right.tl;
      _acc = join(acc, right.hd);
      continue ;
    };
  };
  if (!wlist) {
    return "";
  }
  var w = foldl(wlist.hd, wlist.tl);
  return w._0.name;
}

exports.joinMorphemes = joinMorphemes;
exports.join = join;
exports.fold = fold;
/* No side effect */
